void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _putchar(char c);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int sqrt_check(int g, int c);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int prime_check(int f, int p);
int is_palindrome(char *s);
int check_palindrome(int l, int r, char *p);
int _strlen(char *str);
int wildcmp(char *s1, char *s2);
char *wildcard(char *s3, char *s4);
char *test(char *s5, char *s6, char *t5, char *t6);
